name: Release Go Binaries

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - uses: wangyoucao577/go-release-action@v1.16
      with:
        binary_name: "ssbak"
        asset_name: "ssbak_${{ matrix.goos }}_${{ matrix.goarch }}"
        extra_files: LICENSE README.md
        github_token: ${{ secrets.GITHUB_TOKEN }}
        md5sum: false
        overwrite: true
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        pre_command: export GO386=softfloat CGO_ENABLED=0
        ldflags: -s -w -X "github.com/axllent/ssbak/cmd.Version=${{ env.APP_VERSION }}"
