name: Unit tests

on:
  workflow_call:

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: go test -v ./internal/...
